ssh 1.3

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -33,21 +33,21 @@ jobs:
       #     cache-to: type=inline
       #     platforms: linux/arm64
 
-      - name: Setup SSH Key
-        run: |
-          echo "$REMOTE_SSH_PRIVATE_KEY" > id_rsa
-          chmod 600 id_rsa
-          ssh-keygen -y -f id_rsa > /dev/null && echo "✅ SSH key valid" || echo "❌ SSH key invalid"
-        env:
-          REMOTE_SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
+      # - name: Setup SSH Key
+      #   run: |
+      #     echo "$REMOTE_SSH_PRIVATE_KEY" > id_rsa
+      #     chmod 600 id_rsa
+      #     ssh-keygen -y -f id_rsa > /dev/null && echo "✅ SSH key valid" || echo "❌ SSH key invalid"
+      #   env:
+      #     REMOTE_SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
 
-      # - name: Remote Docker Runner
-      #   uses: thomasvjoseph/remote-docker-runner-action@v1.0.0-rct1.2
-      #   with:
-      #     host: ${{ secrets.SSH_HOST }}
-      #     username: ${{ secrets.SSH_USER }}
-      #     private_key: ${{ secrets.SSH_PRIVATE_KEY }}
-      #     image: thomasjiitak/learn
-      #     container_name: test-app
-      #     docker_username: ${{secrets.DOCKER_USERNAME}}
-      #     docker_password: ${{secrets.DOCKER_PASSWORD}}
+      - name: Remote Docker Runner
+        uses: thomasvjoseph/remote-docker-runner-action@v1.0.0-rct1.3
+        with:
+          host: ${{ secrets.SSH_HOST }}
+          username: ${{ secrets.SSH_USER }}
+          private_key: ${{ secrets.SSH_PRIVATE_KEY }}
+          image: thomasjiitak/learn
+          container_name: test-app
+          docker_username: ${{secrets.DOCKER_USERNAME}}
+          docker_password: ${{secrets.DOCKER_PASSWORD}}
